export { HomeView } from "./home"
export { BasicsView } from "./basics"
export { CreateNftView } from "./createNft"
export { CreateTokenView } from "./createToken"
export { MintTokenView } from "./mintToken"
